<?php

// Plugin definition
$plugin = array(
  'title' => t('Edit Bekræft tur'),
  'category' => t('cua'),
  'icon' => 'cua_editconfirmtur.png',
  'theme' => 'cua_editconfirmtur',
  'css' => 'cua_editconfirmtur.css',
  'regions' => array(
	'mc1' => t('content 1'),
	'mc2' => t('content 2'),
	'mc3' => t('content 3'),
	'mc4' => t('content 4'),
	'mc5' => t('content 5'),
	'mc6' => t('content 6'),
    'mc7' => t('content 7')
  ),
);
