<?php

// Plugin definition
$plugin = array(
  'title' => t('Se lokation 2'),
  'category' => t('cua'),
  'icon' => 'cua_selokation2.png',
  'theme' => 'cua_selokation2',
  'css' => 'cua_selokation2.css',
  'regions' => array(
	'mc1' => t('content 1'),
	'mc2' => t('content 2'),
	'mc3' => t('content 3'),
	'mc4' => t('content 4'),
	'mc5' => t('content 5'),
	'mc6' => t('content 6'),
    'mc7' => t('content 7'),
    'mc8' => t('content 8'),
    'mc9' => t('content 9'),
    'mc10' => t('content 10'),
    'mc11' => t('content 11'),
    'mc12' => t('content 12')
  ),
);
