<?php
function cyklingudenalder_mail($key,&$message,$params){
	switch ($key) {
		case 'send_email':
	    $message['subject']=t($params['subject']);
	    $message['body'][0]=$params['body'];
	    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
			break;
  }
}

/**
* Implementation of hook_hook_info().
*/
function cyklingudenalder_menu() {
  $items['cyklingudenalder/activationemails'] = array(
	  'title' => 'Send Activation emails',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('cykling_activation_form'),
	  'access callback' => array('check_cyklingudenalder_admin'),
	  'type' => MENU_NORMAL_ITEM,
	);
  $items['cyklingudenalder/untagpilot'] = array(
	  'title' => 'Remove pilot from location',
	  'page callback' => 'cyklingudenalder_untag_pilot',
	  'access callback' => TRUE,
	  'type' => MENU_CALLBACK,
	);
	return $items;
}

function cyklingudenalder_untag_pilot(){
	global $user;
	$location_id = filter_xss(arg(2));
	$pilot_id = filter_xss(arg(3));

	$query_removepilot = db_delete('sw_field_data_field_godkendte_piloter')
  	->condition('entity_id', $location_id)
  	->condition('field_godkendte_piloter_uid', $pilot_id)
  	->execute();
	$query_removepilot = db_delete('sw_field_revision_field_godkendte_piloter')
		->condition('entity_id', $location_id)
		->condition('field_godkendte_piloter_uid', $pilot_id)
		->execute();
	$query_removepilot = db_delete('sw_field_data_field_kaptajn')
		->condition('entity_id', $location_id)
		->condition('field_kaptajn_uid', $pilot_id)
		->execute();
	$query_removepilot = db_delete('sw_field_revision_field_kaptajn')
		->condition('entity_id', $location_id)
		->condition('field_kaptajn_uid', $pilot_id)
		->execute();

  $flagg = flag_get_flag('lokation');
  $action = 'unflag';
  $flagg->flag($action, $location_id);
  $truncate_field_cache = db_truncate('sw_cache_field')->execute();
  echo "success";
}

function cykling_activation_form($form, &$form_state){
	$form = array();
	$form['to_emails'] = array(
		'#type' => 'textarea','#title' => 'Enter the recepient E-mails',
	);
	$form['email_subject'] = array(
		'#type' => 'textfield','#title' => 'Email Subject',
	);
	$form['email_body'] = array(
		'#type' => 'textarea','#title' => 'Email Body',
	);
	$form['send_email_submit'] = array(
		'#type' => 'submit','#value' => 'Send Email',
	);
	return $form;
}

function cykling_activation_form_submit($form, &$form_state){
	$to_list = explode(';',$form_state['values']['to_emails']);
	$headers = "MIME-Version: 1.0" . "\r\n";
	$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
	$headers .= 'From: <hej@cyklingudenalder.dk>' . "\r\n";
	$subject = $form_state['values']['email_subject'];
	$email_message = $form_state['values']['email_body'];
	if(count($to_list) > 0){
		foreach($to_list as $to_id){
			$recepient = user_load_by_mail($to_id);
			$activation_link = user_pass_reset_url($recepient);
			$email_message_single = str_replace('!activation_link', $activation_link, $email_message);
			$email_message_single = str_replace('!fname', $recepient->field_fornavn['und'][0]['value'], $email_message_single);
			$email_message_single = str_replace('!user_email', $recepient->mail, $email_message_single);

			$params = array('body' => $email_message_single, 'subject' => $subject, 'headers'=> $headers);
			drupal_mail('cyklingudenalder', 'send_email', $to_id, language_default(), $params, 'hej@cyklingudenalder.dk', TRUE);
		}
	}
}

function check_cyklingudenalder_admin(){
	global $user;
	if($user->uid && $user->uid == 1){
		return TRUE;
	}
	else{
		return FALSE;
	}
}

function pp($str){
	echo '<pre>';
	print_r($str);
	echo '</pre>';
}

function ppe($str){
	echo '<pre>';
	print_r($str);
	echo '</pre>';
	exit;
}

function build_email_text($text){
$activation_email_text = <<<EMAILBODY
"<p>Hej !fname ,</p>

<p>Tak fordi du vil være med i Cykling uden alder!</p>

<p>Du kan logge ind nu ved at klikke på linket herunder, eller ved at copy/paste det ind i din browser:</p>
!activation_link
<p>Ovenstående link kan kun bruges én gang, og vil lede dig hen til en side hvor du kan vælge det password du ønsker.</p>

<p>Efter du har valgt et password, vil du kunne logge ind på http://loop.cyklingudenalder.dk ved at bruge:</p>

<p>Dit brugernavn:  !user_email</p>

<p>God fornøjelse!</p>"
EMAILBODY;

}

function cyklingudenalder_node_presave($node){
//	ppe($node);
}

function cyklingudenalder_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'user_profile_form')
  {
    $form['#submit'][] = 'cycklingudenalder_profile_form_submit';
  }
}

function cycklingudenalder_profile_form_submit($form, &$form_state){
 $form_state['redirect'] = 'lokationer';
}


function cyklingudenalder_views_query_alter(&$view, &$query) {
  if ($view->name == 'calendar_fri_tur' && $view->current_display == 'page_2') {
  $query->where['date']['conditions'][0]['field']="DATE_FORMAT(ADDTIME(FROM_UNIXTIME(field_data_field_tur_dato.field_tur_dato_value2), SEC_TO_TIME(7200)), '%Y-%m-%d') >= :node_date_argument AND DATE_FORMAT(ADDTIME(FROM_UNIXTIME(field_data_field_tur_dato.field_tur_dato_value), SEC_TO_TIME(7200)), '%Y-%m-%d') <= :node_date_argument1";
  }

  if ($view->name == 'calendar_tur' && $view->current_display == 'page_2') {
  $query->where['date']['conditions'][0]['field']="DATE_FORMAT(ADDTIME(FROM_UNIXTIME(field_data_field_tur_dato.field_tur_dato_value2), SEC_TO_TIME(7200)), '%Y-%m-%d') >= :node_date_argument AND DATE_FORMAT(ADDTIME(FROM_UNIXTIME(field_data_field_tur_dato.field_tur_dato_value), SEC_TO_TIME(7200)), '%Y-%m-%d') <= :node_date_argument1";
  }  
  
}


/**
 * Implements hook_theme_registry_alter().
 */
function cyklingudenalder_theme_registry_alter(&$theme_registry) {
  // Kill the next/previous forum topic navigation links.
  /*
   *foreach ($theme_registry['forum_topic_navigation']['preprocess functions'] as $key => $value) {
   *  if ($value = 'template_preprocess_forum_topic_navigation') {
   *    unset($theme_registry['forum_topic_navigation']['preprocess functions'][$key]);
   *  }
   *}
   */

  // to change the Date/week style displayed on top of the Calendar in GO
  $theme_registry['date_nav_title']['function'] = 'cyklingudenalder_theme_date_nav_title';
}

function cyklingudenalder_theme_date_nav_title(&$params) {
  $title  = '';
  $granularity = $params['granularity'];
  $view = $params['view'];
  $date_info = $view->date_info;
  $link = !empty($params['link']) ? $params['link'] : FALSE;
  $format = !empty($params['format']) ? $params['format'] : NULL;
  $format_with_year = variable_get('date_views_' . $granularity . '_format_with_year', 'l, F j, Y');
  $format_without_year = variable_get('date_views_' . $granularity . '_format_without_year', 'l, F j');
  switch ($granularity) {
    case 'year':
      $title = $date_info->year;
      $date_arg = $date_info->year;
      break;

    case 'month':
      $format = !empty($format) ? $format : (empty($date_info->mini) ? $format_with_year : $format_without_year);
      $title = date_format_date($date_info->min_date, 'custom', $format);
      $date_arg = $date_info->year . '-' . date_pad($date_info->month);
      break;

    case 'day':
      $format = !empty($format) ? $format : (empty($date_info->mini) ? $format_with_year : $format_without_year);
      $title = date_format_date($date_info->min_date, 'custom', $format);
      $date_arg = $date_info->year;
      $date_arg .= '-';
      $date_arg .= date_pad($date_info->month);
      $date_arg .= '-';
      $date_arg .= date_pad($date_info->day);
      break;

    case 'week':
      $format = !empty($format) ? $format : (empty($date_info->mini) ? $format_with_year : $format_without_year);
      $title = t('Vecka @date', array(
        '@date' => date_format_date($date_info->min_date, 'custom', $format),
      ));
      $date_arg = $date_info->year . '-W' . date_pad($date_info->week);
      break;
  }
  if (!empty($date_info->mini) || $link) {
    // Month navigation titles are used as links in the mini view.
    $attributes = array('title' => t('View full page month'));
    $url = date_pager_url($view, $granularity, $date_arg, TRUE);
    return l($title, $url, array('attributes' => $attributes));
  }
  else {
    return $title;
  }
}

