<?php

// Plugin definition
$plugin = array(
  'title' => t('Forside AM'),
  'category' => t('cua'),
  'icon' => 'cua_forsideam.png',
  'theme' => 'cua_forsideam',
  'css' => 'cua_forsideam.css',
  'regions' => array(
	'c1' => t('content 1'),
	'c2' => t('content 2'),
	'c3' => t('content 3'),
	'c4' => t('content 4'),
	'c5' => t('content 5'),
	'c6' => t('content 6'),
    'c7' => t('content 7')
  ),
);
